version: '1'

services:

  mysql-database:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql-server
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch-server
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python-server
    ports:
      - "8085:3000"
    environment:
      - DB_Host=mysql-server
      - ES_Host=elasticsearch-server

